"""
Combined PyMC scaffold generator: produces a single Python file
that includes scaffolds for all ranked methods, with the #1 method first.
"""
from __future__ import annotations

from typing import Any


def generate_combined_scaffold(ranked_data: list[dict[str, Any]]) -> str:
    """
    Concatenate all method scaffolds into a single .py file,
    separated by section headers.
    """
    if not ranked_data:
        return "# No methods ranked — re-run the agent to generate scaffold code.\n"

    sections: list[str] = [
        '"""',
        "Combined Measurement Scaffolds — Generated by the Measurement Design Agent",
        "",
        "This file contains PyMC analysis scaffolds for each recommended method,",
        "ordered by suitability score. Start with Method #1.",
        '"""',
        "",
    ]

    for item in ranked_data:
        header = (
            f"# {'=' * 78}\n"
            f"# RANK #{item['rank']}: {item['name']} — {item['score']}/100\n"
            f"# {'=' * 78}\n"
        )
        scaffold = item.get("scaffold", "# Scaffold not available\n")
        sections.append(header)
        sections.append(scaffold)
        sections.append("\n")

    return "\n".join(sections)


def get_top_scaffold(ranked_data: list[dict[str, Any]]) -> str:
    """Return only the scaffold for the top-ranked method."""
    if not ranked_data:
        return "# No methods ranked.\n"
    return ranked_data[0].get("scaffold", "# Scaffold not available\n")
