"""
Markdown narrative report generator.
"""
from __future__ import annotations

from datetime import date
from typing import Any


_SCORE_BAR = {
    (80, 101): "★★★★★",
    (60, 80):  "★★★★☆",
    (40, 60):  "★★★☆☆",
    (20, 40):  "★★☆☆☆",
    ( 0, 20):  "★☆☆☆☆",
}


def _stars(score: float) -> str:
    for (lo, hi), stars in _SCORE_BAR.items():
        if lo <= score < hi:
            return stars
    return "☆☆☆☆☆"


def _list_items(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def generate_report(
    facts: dict,
    ranked_data: list[dict[str, Any]],
) -> str:
    """
    Build a complete Markdown report from elicited facts and ranked method data.
    """
    today = date.today().isoformat()
    kpi = facts.get("kpi", "the key metric")
    objective = facts.get("primary_objective", "campaign effectiveness")
    top = ranked_data[0] if ranked_data else {}
    top_spec = top.get("spec")

    lines: list[str] = [
        f"# Ad Campaign Measurement Design Report",
        f"> Generated by the Measurement Design Agent · {today}",
        "",
        "---",
        "",
        "## 1. Executive Summary",
        "",
        (
            f"This report presents an experimental measurement design for evaluating the "
            f"effectiveness of your ad campaign, with a primary objective of **{objective}** "
            f"and key performance indicator: **{kpi}**."
        ),
        "",
        f"Based on your situation, the recommended approach is the **{top.get('name', 'N/A')}**.",
        f"> {top.get('explanation', top.get('short_description', ''))}",
        "",
        "---",
        "",
        "## 2. What We Learned About Your Situation",
        "",
        f"| Factor | Your Situation |",
        f"|--------|---------------|",
        f"| Primary objective | {facts.get('primary_objective', 'unknown')} |",
        f"| KPI | {facts.get('kpi', 'unknown')} |",
        f"| Randomisation unit | {facts.get('randomization_unit', 'unknown')} |",
        f"| Can run RCT | {'Yes' if facts.get('can_run_rct') else 'No / Uncertain'} |",
        f"| Pre-period history | {facts.get('pre_period_weeks', 'unknown')} weeks |",
        f"| Number of markets | {facts.get('num_markets', 'unknown')} |",
        f"| Geo holdout feasible | {'Yes' if facts.get('geo_holdout_feasible') else 'No'} |",
        f"| Campaign control | {facts.get('campaign_type', 'unknown')} |",
        f"| Rich covariates available | {'Yes' if facts.get('has_rich_covariates') else 'No'} |",
        f"| Audience size estimate | {facts.get('sample_size_estimate', 'unknown')} |",
        f"| Planned campaign duration | {facts.get('test_duration_weeks', 'TBD')} weeks |",
        "",
        "---",
        "",
        "## 3. Method Rankings",
        "",
        "The table below shows how well each method fits your situation (100 = perfect fit).",
        "",
        "| Rank | Method | Score | Fit |",
        "|------|--------|-------|-----|",
    ]

    for item in ranked_data:
        lines.append(
            f"| #{item['rank']} | {item['name']} | {item['score']}/100 | {_stars(item['score'])} |"
        )

    lines += [
        "",
        "---",
        "",
    ]

    # Per-method detail sections
    for item in ranked_data:
        spec = item["spec"]
        if spec is None:
            continue

        lines += [
            f"## {item['rank']}. {item['name']} — {item['score']}/100 {_stars(item['score'])}",
            "",
            f"**Why this score?** {item['explanation']}",
            "",
            f"### Design Details",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| Treatment assignment | {spec.treatment_assignment} |",
            f"| Control definition | {spec.control_definition} |",
            f"| Randomisation unit | {spec.randomization_unit} |",
            f"| Pre-period | {spec.pre_period_weeks or 'N/A'} weeks |",
            f"| Test duration | {spec.test_duration_weeks or 'TBD'} weeks |",
            f"| Statistical approach | {spec.statistical_approach} |",
            f"| Primary model | {spec.primary_model} |",
            f"| MDE | {spec.minimum_detectable_effect} |",
            "",
            "**Pros:**",
            _list_items(spec.pros),
            "",
            "**Cons:**",
            _list_items(spec.cons),
            "",
            "**Key Assumptions:**",
            _list_items(spec.assumptions),
            "",
            "**Data Requirements:**",
            _list_items(spec.data_requirements),
            "",
            "**Implementation Checklist:**",
        ]
        for i, step in enumerate(spec.implementation_steps, start=1):
            lines.append(f"{i}. {step}")
        lines += [
            "",
            "**Caveats:**",
            _list_items(spec.caveats),
            "",
            "---",
            "",
        ]

    lines += [
        "## Appendix: Key Measurement Concepts",
        "",
        "**Incremental lift** — the portion of conversions (or other KPI) that *would not have happened*",
        "  absent the ad campaign. This is what all six methods aim to measure.",
        "",
        "**Counterfactual** — what would have happened if no one had seen the ad.",
        "  Every measurement approach is a different strategy for estimating this unobservable quantity.",
        "",
        "**Randomisation unit** — the entity (user, device, geography) to which treatment/control",
        "  is assigned. Finer units give more statistical power but are not always controllable.",
        "",
        "**Parallel trends assumption (DiD)** — treatment and control groups would have moved",
        "  in the same direction, at the same rate, in the absence of the campaign.",
        "  Visualise pre-period trends to check this.",
        "",
        "*This report was generated automatically. Always have a statistician review the design",
        "before launch.*",
    ]

    return "\n".join(lines)
