"""
A/B Test (Randomized Controlled Trial) method module.
"""
from __future__ import annotations

from .base import ExperimentMethod, DesignSpec, clamp


class ABTest(ExperimentMethod):
    key = "ab_test"
    name = "A/B Test (Randomized Controlled Trial)"
    short_description = (
        "Randomly split your audience into two groups: one that sees the ad (treatment) "
        "and one that does not (control). Compare outcomes directly."
    )

    def score(self, facts: dict) -> float:
        score = 50.0

        # Strongest signal: user-level randomization is possible
        if facts.get("can_run_rct"):
            score += 25
        else:
            score -= 20

        # User or device level is ideal
        if facts.get("randomization_unit") in ("user", "device"):
            score += 15
        elif facts.get("randomization_unit") in ("geo", "market"):
            score -= 10

        # Large audience helps power
        scale = facts.get("sample_size_estimate", "unknown")
        if "large" in scale:
            score += 10
        elif "medium" in scale:
            score += 5
        elif "small" in scale:
            score -= 5

        # A/B doesn't need much historical data
        if not facts.get("has_historical_data"):
            score += 5  # relatively less penalized than other methods

        # Works best with brand control
        if facts.get("campaign_type") == "brand_controlled":
            score += 5
        elif facts.get("campaign_type") == "platform_only":
            score -= 10

        return clamp(score)

    def generate_spec(self, facts: dict, explanation: str = "") -> DesignSpec:
        unit = facts.get("randomization_unit", "user")
        duration = facts.get("test_duration_weeks") or 4

        return DesignSpec(
            method_key=self.key,
            method_name=self.name,
            score=self.score(facts),
            explanation=explanation,
            primary_objective=facts.get("primary_objective", ""),
            kpi=facts.get("kpi", ""),
            treatment_assignment=(
                f"Randomly assign each {unit} to either treatment (ad exposure) "
                "or control (no ad / holdout) using a 50/50 split."
            ),
            control_definition="Holdout group: identical audience segment, ad withheld for full test duration.",
            randomization_unit=unit,
            pre_period_weeks=facts.get("pre_period_weeks"),
            test_duration_weeks=duration,
            num_units=facts.get("sample_size_estimate", "unknown"),
            statistical_approach="Bayesian Beta-Binomial (for rates) or Bayesian Normal (for continuous KPIs).",
            primary_model="Bayesian posterior of treatment effect δ = μ_treatment − μ_control.",
            minimum_detectable_effect="~5% relative lift at 80% power for medium audiences.",
            implementation_steps=[
                "Define treatment and control populations before campaign launch.",
                "Implement {unit}-level holdout in ad platform or CRM.".format(unit=unit),
                "Confirm no overlap between treatment and control segments.",
                "Lock test cell assignments; do not change during flight.",
                "Collect KPI data daily for the full test duration.",
                "Run Bayesian analysis after test ends; report posterior P(treatment > control).",
            ],
            data_requirements=[
                f"Unique {unit} identifier for assignment tracking.",
                f"KPI measurements (e.g., {facts.get('kpi', 'conversions')}) linked back to {unit} IDs.",
                "Ad exposure log (impression/click timestamps per user).",
            ],
            assumptions=[
                "No spillover between treatment and control groups (SUTVA).",
                "Stable unit treatment value assumption holds.",
                "Platform can enforce holdout reliably.",
            ],
            caveats=[
                "If user-level holdout is not possible on the platform, consider Geo Lift instead.",
                "Small audiences (<10k) may require longer test windows or accept wider uncertainty.",
            ],
            pros=[
                "Gold standard for causal inference.",
                "Simple to explain to stakeholders.",
                "Requires no pre-period data.",
            ],
            cons=[
                "Not always feasible if platform controls delivery.",
                "Exposure to anti-competitive signal if holdout leaks.",
            ],
        )

    def generate_scaffold(self, facts: dict) -> str:
        kpi = facts.get("kpi", "conversions")
        unit = facts.get("randomization_unit", "user")
        return f'''"""
A/B Test — Bayesian Analysis Scaffold
KPI: {kpi} | Randomization unit: {unit}
Generated by the Measurement Design Agent
"""
import numpy as np
import pandas as pd
import pymc as pm
import arviz as az
import matplotlib.pyplot as plt

# ── 1. Load your data ──────────────────────────────────────────────────────────
# Expected columns: ["{unit}_id", "group", "{kpi}"]
# group: "treatment" or "control"
df = pd.read_csv("your_ab_results.csv")

treatment = df.loc[df["group"] == "treatment", "{kpi}"].values
control   = df.loc[df["group"] == "control",   "{kpi}"].values

# ── 2. Choose model type ───────────────────────────────────────────────────────
# For binary KPIs (conversion rate), use the Beta-Binomial model below.
# For continuous KPIs (revenue, install count), switch to the Normal model.

# --- Binary KPI model ---------------------------------------------------------
n_t = len(treatment)
n_c = len(control)
conv_t = int(treatment.sum())   # number of conversions in treatment
conv_c = int(control.sum())     # number of conversions in control

with pm.Model() as ab_model:
    # Priors: weakly informative Beta(1, 1) = uniform
    p_treatment = pm.Beta("p_treatment", alpha=1, beta=1)
    p_control   = pm.Beta("p_control",   alpha=1, beta=1)

    # Likelihoods
    obs_t = pm.Binomial("obs_treatment", n=n_t, p=p_treatment, observed=conv_t)
    obs_c = pm.Binomial("obs_control",   n=n_c, p=p_control,   observed=conv_c)

    # Derived quantities
    delta_abs = pm.Deterministic("delta_abs", p_treatment - p_control)
    delta_rel = pm.Deterministic("delta_rel", (p_treatment - p_control) / p_control)
    lift      = pm.Deterministic("prob_treatment_better", pm.math.gt(p_treatment, p_control))

    # Sample
    idata = pm.sample(2000, tune=1000, target_accept=0.9, return_inferencedata=True)

# ── 3. Summarise results ───────────────────────────────────────────────────────
summary = az.summary(idata, var_names=["p_treatment", "p_control", "delta_abs", "delta_rel"])
print(summary)

prob_better = float((idata.posterior["delta_abs"] > 0).mean())
print(f"\\nP(treatment > control) = {{prob_better:.1%}}")

lift_median = float(idata.posterior["delta_rel"].median())
print(f"Median relative lift    = {{lift_median:.1%}}")

# ── 4. Plot posteriors ─────────────────────────────────────────────────────────
az.plot_posterior(idata, var_names=["delta_rel"], ref_val=0)
plt.title("Posterior distribution of relative lift")
plt.tight_layout()
plt.savefig("ab_test_posterior.png", dpi=150)
plt.show()
'''
