"""
Domain prompt templates for the measurement design agent.

These encode expert knowledge about how to interview stakeholders
about experimental design for ad campaign measurement.
"""
from __future__ import annotations

from .system import SYSTEM_PROMPT, WELCOME_MESSAGE
from .questions import (
    TOPIC_QUESTIONS,
    TOPIC_INDEX,
    EXTRACTION_SYSTEM,
    SCORING_EXPLANATION_PROMPT,
)
from .setup_prompts import (
    SETUP_SYSTEM_PROMPT,
    SETUP_WELCOME_TEMPLATE,
    SETUP_TOPIC_QUESTIONS,
    SETUP_TOPIC_INDEX,
    BASELINE_FOLLOWUP_TEMPLATES,
    FEASIBILITY_PREAMBLE_TEMPLATE,
    SETUP_EXTRACTION_SYSTEM,
    SETUP_REPORT_PROMPT,
    REVIEW_RESULTS_PROMPT,
    REVIEW_DECISION_SYSTEM,
    REDESIGN_ELICIT_PROMPT,
    FAQ_SYSTEM_PROMPT,
)

__all__ = [
    "SYSTEM_PROMPT",
    "WELCOME_MESSAGE",
    "TOPIC_QUESTIONS",
    "TOPIC_INDEX",
    "EXTRACTION_SYSTEM",
    "SCORING_EXPLANATION_PROMPT",
    "SETUP_SYSTEM_PROMPT",
    "SETUP_WELCOME_TEMPLATE",
    "SETUP_TOPIC_QUESTIONS",
    "SETUP_TOPIC_INDEX",
    "BASELINE_FOLLOWUP_TEMPLATES",
    "FEASIBILITY_PREAMBLE_TEMPLATE",
    "SETUP_EXTRACTION_SYSTEM",
    "SETUP_REPORT_PROMPT",
    "REVIEW_RESULTS_PROMPT",
    "REVIEW_DECISION_SYSTEM",
    "REDESIGN_ELICIT_PROMPT",
    "FAQ_SYSTEM_PROMPT",
]
